# How to identify terminal residues
# The 1st method in this renaming terminal residue: If a residue number decreases, I assume that a new chain starts (so a former residues should be CXXX). It is possible that I need to identify a terminal residue by counting number of atoms, but so far the current concept works well.

import glob, os, sys

def decide_HID_HIE_HIP(temp_gro_array):
    his_atom_array = []
    for temp_gro_array_line in temp_gro_array:
        atom_name = str(temp_gro_array_line[12:15])
        his_atom_array.append(atom_name)        
    if his_atom_array[1] == " H1":
        return "CHID"
    elif his_atom_array[9] == "CE1":
        return "CHIE"
    else:
        return "CHIP"
# end of decide_HID_HIE_HIP function

def rename_term_by_resnum(input_gro_file_name):
    print "rename_term_by_resnum fn"
    output_gro_file_name = input_gro_file_name[:-4] + "_c_term_renamed_by_resnum.gro"
    temp_gro_file_name = input_gro_file_name[:-4] + "_temp.gro"
    temp_gro_array = []
    very_first_residue = 0
    
    with open(output_gro_file_name, "a+") as f_out:
        with open(temp_gro_file_name, "w") as f_temp:
            with open(input_gro_file_name) as f_in:
                old_residue_num = -1
                ignore_the_first_line = 1 # the first line is about either 'gromacs silly comment' or "Generated by trjconv"
                for line in f_in:
                    if (ignore_the_first_line == 1):
                        ignore_the_first_line = 0
                        f_out.write(line) # we need to write the first line anyway
                        continue
                    splited = line.split( )
                    #print "line: ", line
                    if len(splited) == 5 or len(splited) == 6 or len(splited) == 8 or len(splited) == 9:
                        residue_num = int(line[1:5])
                        if (old_residue_num > residue_num): # never happened to transmin1_gro_by_pdb2gmx.gro
                            #print "new chain & residue start"
                            old_residue_num = residue_num
                            old_residue_num = -1
                            residue_name = str(line[5:8])
                            for temp_gro_array_line in temp_gro_array:
                                former_residue_name = str(temp_gro_array_line[5:9]) # to better marshal, use 5:9 rather than 5:8
                                #print "former_residue_name: ", former_residue_name
                                if former_residue_name == "G   " or former_residue_name == "C   " or former_residue_name == "A   " or former_residue_name == "T   " or former_residue_name == "U   ": 
                                    # if we are dealing with a nucleic acid, don't add C prefix
                                    f_out.write(temp_gro_array_line)
                                elif former_residue_name == "HIS ": # decide among CHID, CHIE, CHIP
                                    new_former_residue_name = decide_HID_HIE_HIP(temp_gro_array)
                                    new_temp_gro_array_line = temp_gro_array_line.replace(former_residue_name, new_former_residue_name)
                                    f_out.write(new_temp_gro_array_line)
                                else:
                                    new_former_residue_name = "C" + former_residue_name[:3]
                                    print "former_residue_name: ", former_residue_name
                                    print "new_former_residue_name: ", new_former_residue_name
                                    new_temp_gro_array_line = temp_gro_array_line.replace(former_residue_name, new_former_residue_name)
                                    f_out.write(new_temp_gro_array_line)

                            #reinitialize temp_gro_array
                            temp_gro_array = []
                            temp_gro_array.append(line)

                        elif (old_residue_num != residue_num):
                            old_residue_num = residue_num
                            if very_first_residue == 0:
                                temp_gro_array.append(line)
                                very_first_residue = 1
                            else: 
                                #print "new residue starts"

                                # it is safe to write to output_gro as is
                                for array_line in temp_gro_array:
                                    f_out.write(array_line)

                                #reinitialize temp_gro_array
                                temp_gro_array = []
                                temp_gro_array.append(line)
    
                        else:
                            temp_gro_array.append(line)
                            old_residue_num = residue_num
                    else: # len(splited) != 5 and len(splited) != 6 and len(splited) != 8 and len(splited) != 9
                        if len(splited) != 3:
                            f_out.write(line)
                        else: # this is for the last line in gro file (3 sums of each)
                            temp_gro_array.append(line)
                # a very last residue is obviously a c-terminal one.
                for temp_gro_array_line in temp_gro_array:
                    former_residue_name = str(temp_gro_array_line[5:9]) # to better marshal, use 5:9 rather than 5:8
                    print "former_residue_name: ", former_residue_name
                    if former_residue_name == "RG  " or former_residue_name == "G   " or \
                        former_residue_name == "C   " or former_residue_name == "A   " or \
                        former_residue_name == "T   " or former_residue_name == "U   ":
                    # if we are dealing with a nucleic acid, don't add C prefix
                        f_out.write(temp_gro_array_line)
                    elif former_residue_name == "MG  " or former_residue_name == "ZN  ":
                    # if we are dealing with a metal, don't add C prefix
                        f_out.write(temp_gro_array_line)
                    elif former_residue_name == "HIS ": # decide among CHID, CHIE, CHIP
                        new_former_residue_name = decide_HID_HIE_HIP(temp_gro_array)
                        new_temp_gro_array_line = temp_gro_array_line.replace(former_residue_name, new_former_residue_name)
                        f_out.write(new_temp_gro_array_line)
                    else:
                        print "len(temp_gro_array_line.split()): ", len(temp_gro_array_line.split())
                        if (len(temp_gro_array_line.split()) != 3):
                            new_former_residue_name = "C" + former_residue_name[:3]
                            new_temp_gro_array_line = temp_gro_array_line.replace(former_residue_name, new_former_residue_name)
                            f_out.write(new_temp_gro_array_line)
                        else:
                            f_out.write(temp_gro_array_line)
    f_in.close()
    f_temp.close()
    f_out.close()
    for to_be_removed_file in glob.glob("*_temp.gro"):
        cmd = "rm " + to_be_removed_file
        os.system(cmd)
    cmd = "rm " + input_gro_file_name
    os.system(cmd)

if (__name__ == "__main__") :
    for to_be_removed_file in glob.glob("*_c_term_renamed*"):
        cmd = "rm " + to_be_removed_file
        os.system(cmd)
    for to_be_removed_file in glob.glob("*_temp.gro"):
        cmd = "rm " + to_be_removed_file
        os.system(cmd)
    args=sys.argv[1:]
    if len(args)<1:
        count = 0
        for gro_file in glob.glob("*.gro"):
            input_gro_file_name = gro_file # if there is only 1 gro file in this folder, use it
            count +=1
            if count == 2:
                print "Please specify one input gro file"
                print "example usage: rename.py input.gro"
                sys.exit("rename_term_res_to_Cres_by_resnum.py exits now (expecting a gro file at next run)")
        rename_term_by_resnum(input_gro_file_name)
    else:
        input_gro_file_name = args[0] # gro input file
        print "[rename_term_res_to_Cres_by_resnum] input_gro_file_name: ", input_gro_file_name
        rename_term_by_resnum(input_gro_file_name)
